// Code generated by logcopter-gen; DO NOT EDIT.

package enrich

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.smailnail.cmd.smailnail.commands.enrich")
