-- 04_other_deep_dive.sql
-- Dig into the 454 "other" messages to find more categories

SELECT
  from_summary,
  COUNT(*) AS cnt
FROM messages
WHERE from_summary NOT LIKE '%notifications@github.com%'
  AND from_summary NOT LIKE '%noreply@github.com%'
  AND from_summary NOT LIKE '%lists.riseup.net%'
  AND from_summary NOT LIKE '%lists.entropia.de%'
  AND from_summary NOT LIKE '%@lists.%'
  AND subject NOT LIKE '[%]%'
  AND from_summary NOT LIKE '%substack.com%'
  AND from_summary NOT LIKE '%mg1.substack.com%'
  AND from_summary NOT LIKE '%mail.beehiiv.com%'
  AND from_summary NOT LIKE '%every.to%'
  AND from_summary NOT LIKE '%ship30for30.com%'
  AND from_summary NOT LIKE '%readwise.io%'
  AND from_summary NOT LIKE '%linkedin.com%'
  AND from_summary NOT LIKE '%facebookmail.com%'
  AND from_summary NOT LIKE '%notifications.soundcloud.com%'
  AND from_summary NOT LIKE '%twitch.tv%'
  AND from_summary NOT LIKE '%accountprotection.microsoft.com%'
  AND from_summary NOT LIKE '%accounts.google.com%'
  AND from_summary NOT LIKE '%paypal.com%'
  AND from_summary NOT LIKE '%bankofamerica.com%'
  AND from_summary NOT LIKE '%ebay.com%'
  AND from_summary NOT LIKE '%e.affirm.com%'
  AND from_summary NOT LIKE '%experian.com%'
  AND from_summary NOT LIKE '%e.usa.experian.com%'
  AND from_summary NOT LIKE '%walgreens.com%'
  AND from_summary NOT LIKE '%amazon.com%'
  AND from_summary NOT LIKE '%cvs.com%'
  AND from_summary NOT LIKE '%manning.com%'
  AND from_summary NOT LIKE '%thetreecenter.com%'
  AND from_summary NOT LIKE '%pledgebox.com%'
  AND from_summary NOT LIKE '%kickstarnow.com%'
  AND from_summary NOT LIKE '%kickstarternew.com%'
  AND from_summary NOT LIKE '%kickstartgenius.com%'
  AND from_summary NOT LIKE '%backerhome.com%'
  AND from_summary NOT LIKE '%backerclub.co%'
  AND from_summary NOT LIKE '%muji.us%'
  AND from_summary NOT LIKE '%taschen%'
  AND from_summary NOT LIKE '%domestika%'
  AND from_summary NOT LIKE '%iphonephotographyschool.com%'
  AND from_summary NOT LIKE '%freelancer.com%'
  AND from_summary NOT LIKE '%replit.com%'
  AND from_summary NOT LIKE '%augmentcode.com%'
  AND from_summary NOT LIKE '%ecamm.com%'
  AND from_summary NOT LIKE '%itch.io%'
  AND from_summary NOT LIKE '%firecrawl.dev%'
  AND from_summary NOT LIKE '%envato%'
  AND from_summary NOT LIKE '%privaterelay.appleid.com%'
  AND from_summary NOT LIKE '%sales.sub-shop.com%'
  AND from_summary NOT LIKE '%rollbar.com%'
  AND from_summary NOT LIKE '%no-reply@%'
  AND from_summary NOT LIKE '%noreply@%'
  AND from_summary NOT LIKE '%[bot]%'
  AND from_summary NOT LIKE '%notification%'
  AND from_summary NOT LIKE '%alert%'
  AND from_summary NOT LIKE '%automated%'
  AND from_summary NOT LIKE '%meetup.com%'
  AND from_summary NOT LIKE '%bozzuto.com%'
  AND from_summary NOT LIKE '%patient-message.com%'
  AND from_summary NOT LIKE '%zulip.com%'
  AND from_summary NOT LIKE '%gmail.com%'
  AND from_summary NOT LIKE '%@bl0rg.net%'
  AND subject NOT LIKE '%security%'
  AND subject NOT LIKE '%verify%'
  AND subject NOT LIKE '%sign-in%'
  AND subject NOT LIKE '%password%'
GROUP BY from_summary
ORDER BY cnt DESC
LIMIT 80;
