// Code generated by logcopter-gen; DO NOT EDIT.

package mirror

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.smailnail.pkg.mirror")
